# Enable mouse
CONFIG_ZMK_POINTING=y
# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Enable deep sleep (15min default) & improve battery life
CONFIG_ZMK_SLEEP=y

# Zephyr Config
CONFIG_USB_DEVICE_HID=y

# Add one more USB_HID_DEVICE: zmk uses HID_0 for keyboard, 
# we use HID_1 for joystick, mouse. or output.
CONFIG_USB_HID_DEVICE_COUNT=2

# Module Config
CONFIG_ZMK_HID_IO=y

# Enable either one of hid joystick / mouse / hid haptic feedback
CONFIG_ZMK_HID_IO_MOUSE=y
